In [ ]:
import numpy as np
#Creating arrays
arr=np.array([1,2,3,4,5],dtype=float)
print(arr)

[1. 2. 3. 4. 5.]


In [ ]:
#zeros
zeros_arr = np.zeros((3,3),dtype=float)
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#ones
ones_arr=np.ones((2,2),dtype=int)
print(ones_arr)

[[1 1]
 [1 1]]


In [ ]:
arange_arr=np.arange(10)
print(arange_arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#array manipulation
arr=np.array([1,2,3,4,5])
reshaped_arr=arr.reshape(5,1)
print(reshaped_arr)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
#slicing
sliced_arr=arr[2:4]
print(sliced_arr)

[3 4]


In [ ]:
import numpy as np
#transpose of array
a=np.array([1,2,3,4,5,6,7,8])
b=a.T
print(b)


[1 2 3 4 5 6 7 8]


In [ ]:
#dot split
b=np.split(a,4)
print(b)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)


[[19 22]
 [43 50]]


In [ ]:
d=np.linalg.eig(c)
print(d)

EigResult(eigenvalues=array([5.80198014e-02, 6.89419802e+01]), eigenvectors=array([[-0.75781077, -0.40313049],
       [ 0.65247439, -0.91514251]]))


In [ ]:
data=np.loadtxt("/content/drive/MyDrive/setdata/harsha.txt.txt",dtype=int)
d=np.savetxt("/content/date.txt",data)
print(d)
print(data)

None
[[1 2 3 4 5]
 [2 3 4 6 7]
 [2 3 4 5 6]]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
arange_arr=np.arange(0,1000,5)
print(arange_arr)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


In [ ]:
f=np.savetxt("/content/ga.txt",arange_arr)

In [ ]:
data1=np.loadtxt("//content/ga.txt",dtype=int)
print(data1)


[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


<ipython-input-5-3daacfe19d73>:1: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  data1=np.loadtxt("//content/ga.txt",dtype=int)


In [ ]:
#random function
a=np.random.rand()
print(a)
b=np.random.randint(2,10)
print(b)
c=np.random.randint(1,10,5)
print(c)


0.2897322786758094
5
[2 8 4 5 3]


In [ ]:
c=np.array([[1,2,3],[2,4,5]])
print(type(c))
print(c.ndim)
print(c.shape)

<class 'numpy.ndarray'>
2
(2, 3)


In [ ]:
a=np.linspace(0.8,2,5)
print(a)

[0.8 1.1 1.4 1.7 2. ]


In [ ]:
a=np.arange(6).reshape(2,3)
print(a)


[[0 1 2]
 [3 4 5]]


In [ ]:
b=np.arange(24).reshape(2,3,4)
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
b=np.arange(24).reshape(2,3,4)
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
a=np.array([[1,2],[2,5]])
b=np.array([[1,3],[2,4]])
print(a*b)
print(a@b)
c=np.dot(a,b)
print(c)


[[ 1  6]
 [ 4 20]]
[[ 5 11]
 [12 26]]
[[ 5 11]
 [12 26]]


In [ ]:
from numpy import random
a=np.ones((2,3),dtype=int)
print(a)
print(a.sum())
b=np.ones((2,3),dtype=float)
print(b.sum())
print(a.sum(axis=1))

print(a.sum(axis=0))

[[1 1 1]
 [1 1 1]]
6
6.0
[3 3]
[2 2 2]


In [ ]:
a=np.floor(np.random.random((2,12)))
print(a)
c=np.random.random((2,12))
print(c)
d=np.random.random((2,2))
print(d)
a=np.ceil(np.random.random((2,12)))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0.4915413  0.85525902 0.28270754 0.55698556 0.94542411 0.64521121
  0.23395986 0.02816426 0.17603933 0.82199727 0.82892995 0.2128293 ]
 [0.86783919 0.90087456 0.605504   0.62076189 0.40481737 0.8384946
  0.41799985 0.72480827 0.94477481 0.57504788 0.30775679 0.85279554]]
[[0.04642558 0.20847342]
 [0.03445381 0.19344842]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
from numpy import random
b=np.ones((2,3),dtype=int)
print(b.max())
print(b.max(axis=1))

print(b.max(axis=0))

1
[1 1]
[1 1 1]


In [ ]:
a=np.array([[1,2],[2,5]])
print(a.max())
print(a.max(axis=1))

print(a.max(axis=0))


5
[2 5]
[2 5]


In [ ]:
a=np.array([[1,2],[2,5]])
#print(a.cumsum())
print(a.cumsum(axis=1))

print(a.cumsum(axis=0))

[[1 3]
 [2 7]]
[[1 2]
 [3 7]]


In [ ]:

a=np.array([[2,3,5,6]])

print(a.cumsum(axis=1))


[[ 2  5 10 16]]


In [ ]:
a=np.array([2,3,5,6,1,2])
a.resize(3,2)
#b=a.resize(3,2)
print(a)
print(a.shape)


[[2 3]
 [5 6]
 [1 2]]
(3, 2)


In [ ]:
a=np.array([2,3,5,6,1,2])
a.resize(2,3)
print(a)
b=np.array([7,8,9,10,11,12,])
b.resize(2,3)
print(b)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[2 3 5]
 [6 1 2]]
[[ 7  8  9]
 [10 11 12]]
[[ 2  3  5]
 [ 6  1  2]
 [ 7  8  9]
 [10 11 12]]
[[ 2  3  5  7  8  9]
 [ 6  1  2 10 11 12]]


In [ ]:
a=np.arange(0,30).reshape(2,3,5)
print(a)
print(np.dstack(a))


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
a=10
print(a)

10


In [ ]:
a=True
print(a)

True


In [ ]:
12/5

2.4

In [ ]:
#24/02/23
import numpy as np
a=np.eye(4)#diagonal wise to print 1
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
a=np.full((2,2),3)
print(a)
print(a.itemsize)

[[3 3]
 [3 3]]
8


In [ ]:
x=[1,2,3]
a=np.asarray(x)#symetric
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
x=np.array([1,4,0],float)
y=np.array([2,2,1],float)
print(np.inner(x,y))#1*2+ 4*2 +0*1
print(np.outer(x,y))#first element multiply with all elements in 2nd array
print(np.cross(x,y))


10.0
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
[ 4. -1. -6.]


In [ ]:
a=np.array([1.2,3.2,2.1,3.4,2.4,3.5,5.1])#.5 above means next value will come//below .5 means below value will come
np.rint(a)


array([1., 3., 2., 3., 2., 4., 5.])

In [ ]:
a=np.array([1,3,2,4,24])#.a array/b.array of each element
b=np.array([2,32,21,3,2])
print(np.true_divide(a,b))

[ 0.5         0.09375     0.0952381   1.33333333 12.        ]


In [ ]:
a=np.array([1,1,2,2,3,3])
print(np.unique(a))#to print unique elements

[1 2 3]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[4,5],[6,7]])
print(np.union1d(a,b))#it will convert into 1d array and it will  print repeated elements once only

[1 2 3 4 5 6 7]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[4,5],[6,7]])
print(np.intersect1d(a,b))#common element
print(np.setdiff1d(a,b))#a-b in sets

[4]
[1 2 3]


In [ ]:
a=8#to find hypotenuse
b=6
c=np.hypot(a,b)
print(c)

10.0


In [ ]:
x=np.sin(0)
print(x)

0.0


In [ ]:
a=np.array([10,20,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.divmod(a,b)#1st matrix quotient and 2nd matrix remainder
print(c)
c=np.mod(a,b)
print(c)
c=np.divide(a,b)#exact answer
print(c)

(array([ 0,  0, 15,  2,  2,  2]), array([10, 20,  0,  0,  0, 10]))
[10 20  0  0  0 10]
[ 0.5         0.95238095 15.          2.          2.          2.4       ]


In [ ]:
a=np.array([10,20,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.multiply(a,b)#element matrix
print(c)
c=np.matmul(a,b)
print(c)

[ 200  420   60  800 1250 1500]
4230


In [ ]:
from numpy import random
x=random.normal(size=(2,3))#.normal is guassian distribution
print(x)
x=random.normal(loc=1,scale=2,size=(2,3))#loc=mean ,scale =standard deviation
print(x)

[[ 0.81981001  0.3855947  -1.11361529]
 [ 1.48455398  0.24012845  0.99875584]]
[[ 2.97786146  0.96515812  0.97026951]
 [-2.50588    -0.38339347  4.04774307]]


In [ ]:
x=random.binomial(n=12,p=0.5,size=10)#n=no of trials p=probability size=10 elements
print(x)
x=random.poisson(lam=2,size=10)#poisson distribution function
print(x)

[7 6 7 8 4 4 8 4 8 6]
[1 3 2 3 2 2 1 3 1 4]


In [ ]:
x=random.choice([1,2,3,4,5])#any one choice will select
print(x)
x=random.choice([3,5],p=[0.2,0.8],size=(3,5))
print(x)
y=random.choice([3,5],p=[0.5,0.5],size=(3,5))
print(y)

1
[[5 5 5 3 3]
 [5 3 5 5 5]
 [5 3 3 5 5]]
[[5 3 5 3 5]
 [3 3 3 5 5]
 [5 3 3 3 5]]
